---
title: "Nextreme_EGLV"
author: "Dimitri Falk"
date: 2026-02-25
output: rmarkdown::html_vignette
vignette:  >
  %\VignetteIndexEntry{Nextreme_EGLV}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6,
  collapse = TRUE,
  comment = "#>"
)
```

# Installation

```{r, eval = FALSE}
# install.packages("pak")
pak::pak("dimfalk/Nextreme")
```

```{r}
library("tictoc")

library("timeseriesIO")
library("Nextreme")
library("kostra2020")
```

# Getting started

## 1. Load timeseries data

```{r}
tic()

# 5-minutely sums 1931-2025; caution: 263 MB!
fname <- "../inst/exdata/n2582_01011931-01012026_5minutenwerte_sum.csv"

# read TD export as xts
prec <- timeseriesIO::read_td_csv(fname)

# conversion to data.frame, as expected by `{Nextreme}`
prec.df <- zoo::fortify.zoo(prec)

# clean colnames
colnames(prec.df) <- c("Datum", "RH")

# inspect
head(prec.df)

tail(prec.df)

toc()
# 186 s
```

## 2.1 Generate AMS

```{r}
tic()

dur <- c(5, 10, 15, 20, 30, 45, 60, 90, 120, 180, 240, 360, 540, 720, 1080, 1440, 2880, 4320, 5760, 7200, 8640, 10080)

maxVolSerie <- jaehrliche_maxSerie(prec.df, 
                                   Dauern = dur, 
                                   DSDmin = 240, 
                                   Intervall = 5,
                                   SerieTyp = "VOL")

head(maxVolSerie)

toc()
# 561 s
```

## 2.2 Correct for interval widths

```{r}
tic()

maxVolSerie_korr <- Intervall_Korrektur(maxVolSerie, Intervall = 5)

head(maxVolSerie_korr)

# mittlere relative Abweichung entspricht dem verwendeten Korrekturfaktor
all.equal(maxVolSerie, maxVolSerie_korr)

# dump to disk
write.csv2(maxVolSerie, file = "jSe_2582_unkorr.csv")
write.csv2(maxVolSerie_korr, file = "jSe_2582_korr.csv")

toc()
# 0.13 s
```

## 3.1 GEV parameters estimation

```{r}
tic()

N_pars <- Parameter_Schaetzung(maxVolSerie_korr, 
                               Dauern = dur, 
                               methGEV = "GEV", 
                               formTyp = "FIX", 
                               Gamma = -0.1,
                               SerieTyp = "VOL")
N_pars

# dump to disk
write.csv2(N_pars, file = "N_pars_2582.csv", row.names = FALSE)

toc()
# 19 s
```

## 3.2 Precipitation depth estimation

```{r}
tic()

tn <- c(1, 2, 3, 5, 10, 20, 30, 50, 100)

H_quas <- Quantil_Schaetzung(N_pars, 
                             Dauern = dur,
                             Tn = tn, 
                             methGEV = "GEV",
                             SerieTyp = "VOL")

colnames(H_quas) <- paste0("D", dur)
rownames(H_quas) <- tn

t(H_quas) |> tibble::as_tibble()

# dump to disk
t(H_quas) |> write.csv2(file = "H_quas_2582.csv")

toc()
# 1 s
```

## 3.3 Uncertainty estimation

```{r, eval = FALSE}
tic()

UC <- Unsicherheit_Schaetzung(maxIntSerie_korr,
                              Dauern = dur,
                              methGEV = "GEV",
                              formTyp = "FIX",
                              Gamma = -0.1,
                              SerieTyp = "VOL",
                              Tn = tn,
                              nBoots = 100,
                              rSeed = 42,
                              Konfidenzgrenzen = c(0.025, 0.975))

toc()
# 2860 s

# extract parameters and quantiles
PAR_UC <- UC$PAR_INFO
HN_UC <- UC$QUA_INFO
```

```{r, echo = TRUE, eval = TRUE}
plot(dur, H_quas["100", ], type = "l", lwd = 2, lty = 2, log = "xy",
     ylim = range(HN_UC$`97.5%`["100", ], HN_UC$`2.5%`["100", ]), col = "red",
     ylab = "hN [mm]", xlab = "Dauerstufe [min]", main = "2582 GE-Altstadt PWK, Tn = 100")

polygon(c(dur, rev(dur)), 
        c(HN_UC$`2.5%`["100", ], rev(HN_UC$`97.5%`["100", ])), 
        col = "royalblue", border = NA)

lines(dur, HN_UC$Mittelwert["100",], type = "l", col = "royalblue4", lwd = 2)

lines(dur, H_quas["100",], type = "l", col = "red", lwd = 2, lty = 2)

legend("topleft", 
       c("95 % Konfidenzintervall", "Mittelwert", "hN"),
       col = c("royalblue", "royalblue4", "red"), 
       lty = c(1, 1, 2), 
       lwd = c(10, 2, 2),
       bty = "n")
```

```{r, echo = TRUE, eval = TRUE}
UC_relUC <- round(HN_UC$rel.Unsicherheit, 2)

# Option 1 
barplot(as.matrix(UC_relUC), col = Tn_Farbe, ylab = "relative Unsicherheit [%]",  xlab = "Dauerstufe [min]",
        main = "Station 01684")
legend("top", legend = c(2, 5, 10, 20, 50, 100), fill = Tn_Farbe, cex = 0.8, 
       title = "Tn", horiz = TRUE, bty = "n")

# Option 2 
barplot(as.matrix(UC_relUC),col = Tn_Farbe, beside = TRUE, ylim = c(0, 50), ylab = "relative Unsicherheit [%]",
        xlab = "Dauerstufe [min]", main = "Station 01684")
legend("top", legend = c(2, 5, 10, 20, 50, 100), fill = Tn_Farbe, cex = 0.8, 
       title = "Tn", horiz = TRUE, bty = "n")

# Option 3 
Dauer_Farbe = hcl.colors(dim(UC_relUC)[2], "blues", rev = TRUE)

barplot(as.matrix(t(UC_relUC)), col = Dauer_Farbe, beside = TRUE, ylim = c(0, 60), 
        ylab = "relative Unsicherheit [%]", xlab = "Tn", main = "Station 01684")
legend("top", legend = Dauern, fill = Dauer_Farbe, cex = 0.8, title = "Dauerstufe [min]",
       bty = "n", ncol = 6)
```

## 4. Compare values with KOSTRA-DWD-2020

```{r}
coords <- c(366889.91, 5707517.24)

p <- kostra2020::get_centroid(coords, crs = "epsg:25832")
p

idx <- kostra2020::get_idx(p)
idx

stats <- kostra2020::get_stats(idx)
stats

kostra2020::get_returnp(stats, hn = 58.6, d = 360)

# --- using parameters directly ---

params <- kostra2020::get_params(idx)
params

# TODO: Nextreme#8
Quantil_Schaetzung(as.data.frame(params), 
                   Dauern = dur,
                   Tn = tn, 
                   methGEV = "GEV",
                   SerieTyp = "VOL")

Tn_Schaetzung(as.data.frame(params), hN = 58.6, Dauern = 360, methGEV = "GEV")
```
